INSERT INTO theme VALUES(NULL,'ActionScript','Langage de programmation utilisé au sein d\'applications clientes (comme Adobe Flash et Adobe Flex)');
INSERT INTO theme VALUES(NULL,'AppleScript','Langage de script créé par Apple, et intégré à Mac OS');
INSERT INTO theme VALUES(NULL,'C++','Langage compilé, permettant la programmation procédurale, la programmation orientée objet et la programmation générique');
INSERT INTO theme VALUES(NULL,'C#','Langage de programmation orienté objet, créé par la société Microsoft');
INSERT INTO theme VALUES(NULL,'CoffeeScript','Langage de programmation, qui se compile en JavaScript');
INSERT INTO theme VALUES(NULL,'D','Langage de programmation impératif orienté objet et multi-paradigmes conçu pour la programmation système');
INSERT INTO theme VALUES(NULL,'Eiffel','Langage de programmation orienté objet (POO)');
INSERT INTO theme VALUES(NULL,'Groovy','Langage de programmation orienté objet destiné à la plate-forme Java');
INSERT INTO theme VALUES(NULL,'Java','La particularité de Java est que les logiciels écrits dans ce langage doivent être très facilement portables');
INSERT INTO theme VALUES(NULL,'JavaScript','Langage de programmation de scripts principalement employé dans les pages web interactives mais aussi pour les serveurs');
INSERT INTO theme VALUES(NULL,'Logo','Logo est à la fois une philosophie de l’éducation et une famille de langages de programmation en constante évolution');
INSERT INTO theme VALUES(NULL,'Objective-C','L\'Objective-C est un langage de programmation orienté objet réflexif');
INSERT INTO theme VALUES(NULL,'PHP','Principalement utilisé pour produire des pages Web dynamiques via un serveur HTTP');
INSERT INTO theme VALUES(NULL,'Python','Il favorise la programmation impérative structurée, fonctionnelle et orientée objet');
INSERT INTO theme VALUES(NULL,'Ruby','Langage de programmation libre. Il est interprété, orienté objet');
INSERT INTO theme VALUES(NULL,'Smalltalk','Smalltalk a été d\'une grande influence dans le développement de nombreux langages de programmation');
INSERT INTO theme VALUES(NULL,'VisualBasic','Langage de programmation événementielle de troisième génération ainsi qu\'un environnement de développement intégré, créé par Microsoft');
INSERT INTO theme VALUES(NULL,'ASP','Ensemble de logiciels développés par Microsoft et utilisés dans la programmation Web.');
INSERT INTO theme VALUES(NULL,'Assembleur','L\'angage de bas niveau qui représente le langage machine');
INSERT INTO theme VALUES(NULL,'C','Langage de programmation impératif et généraliste.');
INSERT INTO theme VALUES(NULL,'COBOL','Langage commun pour la programmation d\'applications de gestion');